Vagrant.configure(2) do |config| 
    config.vm.box = "centos/7"
    config.vm.hostname = "jenkins"
    config.vm.box_check_update = false
    
    config.vm.provider "hyperv" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
    config.vm.provision :shell, path: "init.sh"
  end
  