Vagrant.configure(2) do |config| 
    config.vm.box = "centos/7"
    config.vm.hostname = "grafana"
    config.vm.box_check_update = false
    config.vm.network "private_network", ip: "192.168.1.50"
    
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1048"
      vb.cpus = "1"
    end
    config.vm.provision :shell, path: "init.sh"
  end
  