Vagrant.configure(2) do |config| 
    config.vm.box = "centos/7"
    config.vm.hostname = "pxe"
    config.vm.box_check_update = false    
    config.vm.provider "hyperv" do |vb|
      vb.memory = "1048"
      vb.cpus = "2"
    end
    config.vm.provision :shell, path: "init.sh"
  end
  